# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  Martin
subtitle: Martin's blog
name: Martin
email: 865026758@qq.com
description: 本站是Martin做大梦的地方，偶尔分享，爱看不看。诚实笑.jpg
keywords: 白日梦想家,java,python,spring,springmvc,mybatis,hibernate,ssh,ssm
encoding: "utf-8"
favicon: favicon.ico

repository: Mart1nch/Mart1nch.github.io
github_url: https://github.com/Mart1nch
cnblog_url: http://www.cnblogs.com/mart1n
csdn_url:https://blog.csdn.net/Mart1nn
url: https://Mart1nch.github.io
enforce_ssl: mart1n.cn

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata
  - jekyll-octicons
  
# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:

  -
    href: /
    label: Home

#   -
#     href: /spring-boot.html
#     label: Spring-Boot

#   -
#     href: /spring-cloud.html
#     label: Spring-Cloud

  -
    href: /archives.html
    label: Archives

  -
    href: /link.html
    label: Link

  -
    href: /about.html
    label: About


# labels. my blog key words
labels:

  -
    href: /share/2017/10/01/resource-sharing.html
    name: 资源

  -
    href: /life.html
    name: 故事

  -
    href: /arch.html
    name: 架构
    
  -
    href: /jvm.html
    name: Jvm

#   -
#     href: /fastdfs.html
#     name: FastDFS

#   -
#     href: /mongodb.html
#     name: MongoDB

#   -
#     href: /docker.html
#     name: Docker

  -
    href: /open-source.html
    name: Code   

  -
    href: /it.html
    name: It   

# selected articles
classes:

  -
    href: /life.html
    name: 我的故事
    describe: 生活就是故事，故事就是生活

  -
    href: /arch.html
    name: 架构师之路
    describe: 一个架构师的自我修养

  -
    href: /jvm.html
    name: Jvm系列文章
    describe: Java之根基，Java程序员必学


# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: Mart1nch
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: Mart1nch
    repo: Mart1nch.github.io
    oauth:
        client_id: fa13204961b0ef4842d9
        client_secret: 732472a601f9eee7e119addf253e8f24c8baeb6f
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: Mart1nch
    repo: Mart1nch.github.io
    clientID: fa13204961b0ef4842d9
    clientSecret: 732472a601f9eee7e119addf253e8f24c8baeb6f
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true
